# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.22"
  amd64: "ghcr.io/home-assistant/amd64-base:3.22"
  armhf: "ghcr.io/home-assistant/armhf-base:3.22"
  armv7: "ghcr.io/home-assistant/armv7-base:3.22"
  i386: "ghcr.io/home-assistant/i386-base:3.22"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Zigbee2MQTT WindFront"
  org.opencontainers.image.description: "Zigbee2MQTT WindFront standalone frontend."
  org.opencontainers.image.source: "https://github.com/Nerivec/ha-zigbee2mqtt-windfront"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  WINDFRONT_VERSION: "v2.2.3"
