name: Bump version

on:
  workflow_dispatch:
    inputs:
      app:
        description: "The folder of the app to version bump"
        required: true
        default: "windfront"
        type: choice
        options: ["windfront"]
      arg_name:
        description: "The name of the version to bump (without '_VERSION')"
        required: true
        default: "WINDFRONT"
        type: string
      version:
        description: "The new version"
        required: true
        type: string
      changelog:
        description: "The changelog to write if needed"
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Bump ${{ inputs.app }} app ${{ inputs.arg_name }} to ${{ inputs.version }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Bump version & write changelog
        run: |
          sed -i -E 's/^ARG ${{ inputs.arg_name }}_VERSION=.*$/ARG ${{ inputs.arg_name }}_VERSION=${{ inputs.version }}/g' ./${{ inputs.app }}/Dockerfile

          appFolderLower=$(echo "${{ inputs.app }}" | tr '[:upper:]' '[:lower:]')
          argNameLower=$(echo "${{ inputs.arg_name }}" | tr '[:upper:]' '[:lower:]')

          if [[ "$appFolderLower" == "$argNameLower" ]]; then
            sed -i -E 's/^version: .*$/version: "${{ inputs.version }}"/g' ./${{ inputs.app }}/config.yaml
          fi

          if [[ -z "${{ inputs.changelog }}" ]]; then
            echo "No changelog to write"
          else
            echo -e "${{ inputs.changelog }}\n\n$(cat ./${{ inputs.app }}/CHANGELOG.md)" > ./${{ inputs.app }}/CHANGELOG.md
          fi

          branch="${{ inputs.app }}-${{ inputs.arg_name }}-${{ inputs.version }}"
          title="fix: bump ${{ inputs.app }} app ${{ inputs.arg_name }} to ${{ inputs.version }}"

          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b "$branch"
          git add .
          git commit -m "$title" || echo 'Nothing to commit'
          git push origin "$branch"

          echo -e "${{ inputs.changelog }}" | gh pr create \
            --fill \
            --base main \
            --head $branch \
            --title "$title" \
            --body-file -

          gh pr merge $branch --squash --auto --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
