name: Manual Builder

env:
  REGISTRY: ghcr.io

on:
  workflow_dispatch:
    inputs:
      app:
        description: "The folder of the add-on to build"
        required: true
        default: "windfront_edge"
        type: choice
        options: ["windfront", "windfront_edge"]
      publish:
        required: true
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  build-app:
    name: Build ${{ inputs.app }}
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/build-app.yaml
    with:
      app: ${{ inputs.app }}
      publish: ${{ inputs.publish }}
    secrets: inherit
